 <div class="container">
        <div class="text-left mb-4">
            <h1 class="display-4">Сайт: <?= htmlspecialchars($url['name']) ?></h1>
        </div>
        <table data-test="url" class="table">
            <tbody>
            <tr>
                <th scope="col">ID</th>
                <td><?= htmlspecialchars($url['id']) ?></td>
            </tr>
            <tr>
                <th scope="col">Имя</th>
                <td><?= htmlspecialchars($url['name']) ?></td>
            </tr>
            <tr>
                <th scope="col">Дата создания</th>
                <td><?= htmlspecialchars($url['created_at']) ?></td>
            </tr>
            </tbody>
        </table>
    </div>

    <div class="text-left mb-4">
        <h1 class="display-4">Проверки</h1>
    </div>
    <form method="post" action="/urls/{id}/cheks">
        <input type="submit" value="Запустить проверку">
    </form>
    <table data-test="checks" class="table">
        <thead>
        <tr>
            <th scope="col">ID</th>
            <th scope="col">Код ответа</th>
            <th scope="col">h1</th>
            <th scope="col">title</th>
            <th scope="col">description</th>
            <th scope="col">Дата создания</th>
        </tr>
        </thead>
        <tbody>
            <tr>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
            </tr>
        </tbody>
    </table>
 </div>
