<div class="container d-flex justify-content-center align-items-center min-vh-100">
    <div class="text-center">
        <img src="/images/404.jpg" alt="404 Not Found" class="img-fluid" style="max-width: 600px;">
        <h1 class="mt-4">Страница не найдена</h1>
        <p>Запрашиваемая страница не существует</p>
        <a href="<?= $router->urlFor('home') ?>" class="btn btn-primary">Вернуться на главную</a>
    </div>
</div>
