 <div class="container mt-5">
     <div class="row justify-content-center">
         <div class="col-md-8 col-lg-6 bg-secondary-subtle rounded-4 p-4 p-md-5 shadow-sm">
             <div class="text-center mb-4">
                 <h1 class="display-4">Анализатор страниц</h1>
                 <p class="lead">Бесплатно проверяйте сайты на SEO-пригодность</p>
             </div>
             <form action="/urls" method="post">
                 <div class="input-group input-group-lg">
                     <input
                             type="url"
                             name="url"
                             class="form-control"
                             placeholder="https://www.example.com"
                             required
                             value="<?= htmlspecialchars($term ?? '') ?>"
                     />
                     <button class="btn btn-primary" type="submit">
                         ПРОВЕРИТЬ
                     </button>
                 </div>
             </form>
         </div>
     </div>
 </div>
