<!doctype html>
<html lang="ru">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Анализатор страниц</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
</head>
<body>
<header>
    <nav class="navbar bg-dark border-bottom border-bottom-dark" data-bs-theme="dark">
        <div class="container-fluid d-flex justify-content-start">
            <a class="navbar-brand" href="#">Анализатор страниц</a>
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="#">Сайты</a>
                </li>
            </ul>
        </div>
    </nav>
</header>
<main class="container">
    <?php if(!empty($flash)): ?>
        <?php foreach ($flash as $key => $messages): ?>
            <?php foreach ($messages as $message): ?>
                <div class="alert alert-<?= $key === 'error' ? htmlspecialchars('danger') : htmlspecialchars($key) ?>">
                    <?= htmlspecialchars($message) ?>
                </div>
            <?php endforeach; ?>
        <?php endforeach; ?>
    <?php endif; ?>
    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-md-8 col-lg-6 bg-secondary-subtle rounded-4 p-4 p-md-5 shadow-sm">
                <div class="text-center mb-4">
                    <h1 class="display-4">Анализатор страниц</h1>
                    <p class="lead">Бесплатно проверяйте сайты на SEO-пригодность</p>
                </div>
                <form action="/urls" method="post">
                    <div class="input-group input-group-lg">
                        <input
                                type="url"
                                name="url"
                                class="form-control"
                                placeholder="https://www.example.com"
                                required
                                value="<?= htmlspecialchars($term ?? '') ?>"
                        />
                        <button class="btn btn-primary" type="submit">
                            ПРОВЕРИТЬ
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</main>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
</body>
</html>