<!doctype html>
<html lang="ru">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Сайт</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
</head>
<body>
<header>
    <nav class="navbar bg-dark border-bottom border-bottom-dark" data-bs-theme="dark">
        <div class="container-fluid d-flex justify-content-start">
            <a class="navbar-brand" href="/">Анализатор страниц</a>
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="/urls">Сайты</a>
                </li>
            </ul>
        </div>
    </nav>
</header>
<main class="container">
    <?php if(!empty($flash)): ?>
        <?php foreach ($flash as $key => $messages): ?>
            <?php foreach ($messages as $message): ?>
                <div class="alert alert-<?= $key === 'error' ? htmlspecialchars('danger') : htmlspecialchars($key) ?>">
                    <?= htmlspecialchars($message) ?>
                </div>
            <?php endforeach; ?>
        <?php endforeach; ?>
    <?php endif; ?>
    <div class="container">
        <div class="text-left mb-4">
            <h1 class="display-4">Сайт: <?= htmlspecialchars($url['name']) ?></h1>
        </div>
        <table data-test="url" class="table">
            <tbody>
            <tr>
                <th scope="col">ID</th>
                <td><?= htmlspecialchars($url['id']) ?></td>
            </tr>
            <tr>
                <th scope="col">Имя</th>
                <td><?= htmlspecialchars($url['name']) ?></td>
            </tr>
            <tr>
                <th scope="col">Дата создания</th>
                <td><?= htmlspecialchars($url['created_at']) ?></td>
            </tr>
            </tbody>
        </table>
    </div>

    <div class="text-left mb-4">
        <h1 class="display-4">Проверки</h1>
    </div>
    <form method="post" action="/urls/{id}/cheks">
        <input type="submit" value="Запустить проверку">
    </form>
    <table data-test="checks" class="table">
        <thead>
        <tr>
            <th scope="col">ID</th>
            <th scope="col">Код ответа</th>
            <th scope="col">h1</th>
            <th scope="col">title</th>
            <th scope="col">description</th>
            <th scope="col">Дата создания</th>
        </tr>
        </thead>
        <tbody>
            <tr>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
            </tr>
        </tbody>
    </table>
    </div>
</main>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
</body>
</html>